# Generated by Django 3.1.3 on 2020-11-06 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0002_auto_20201106_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='bakery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='bakery.bakery'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('bakery', 'name')},
        ),
    ]
